org: aquijuz
app: serverless-framework-2-lambda
service: serverless-framework-2-lambda
frameworkVersion: '3'

resources:
  extensions:
    S3BucketAlunoscsv:
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - POST
                - PUT
                - GET
                - HEAD
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"

params:
  dev:
    bucket: alunos-csv-local
  prod:
    bucket: alunos-csv

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - s3:GetObject
          Resource: 
            - arn:aws:s3:::alunos-csv/*
  environment:
    STAGE: ${sls:stage}

functions:
  cadastrarAlunos:
    handler: cadastro_batch/index.cadastrarAlunos
    events:
      - s3:
          bucket: ${param:bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

  simulandoUploadDoCsv:
    handler: cadastro_batch/local/index.simulandoUploadDoCsv
    events:
      - httpApi:
          path: /alunos/batch
          method: post
    enabled: false

  enviaUrlPreassinada:
    handler: presigned_url/index.enviaUrlPreassinada
    events:
      - httpApi:
          path: /alunos/presignurl
          method: post

custom:
  serverless-offline:
    httpPort: 3001

plugins:
  - serverless-offline
  - serverless-s3-local
  - serverless-disable-functions
